/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_lab_ugcmodule_media_ffmpeg_FFmpegNative */

#ifndef _Included_com_lab_ugcmodule_media_ffmpeg_FFmpegNative
#define _Included_com_lab_ugcmodule_media_ffmpeg_FFmpegNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_lab_ugcmodule_media_ffmpeg_FFmpegNative
 * Method:    run
 * Signature: ([Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_lab_ugcmodule_media_ffmpeg_FFmpegNative_run
  (JNIEnv *, jclass, jobjectArray);

/*
 * Class:     com_lab_ugcmodule_media_ffmpeg_FFmpegNative
 * Method:    registerCallbackForFFmpeg
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_lab_ugcmodule_media_ffmpeg_FFmpegNative_registerCallbackForFFmpeg
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif

void showLogForJava(char* input);
